### ISSUE TITLE
lein uberjar fails on debian buster

### ISSUE THREAD

**Issue by faxm0dem** [anthonygalea/riemann-console#1]
```
☠ lein with-profile prod uberjar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core__init.load(Unknown Source)
        at clojure.core__init.<clinit>(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.lang.RT.doInit(RT.java:461)
        at clojure.lang.RT.<clinit>(RT.java:331)
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2181)
        at clojure.instant$loading__5569__auto____6869.invoke(instant.clj:9)
        at clojure.instant__init.load(Unknown Source)
        at clojure.instant__init.<clinit>(Unknown Source)
        ... 23 more
```

**Comment by anthonygalea** [comment]
Thanks for reporting this Fabien. Can you share your lein and java versions?

**Comment by faxm0dem** [comment]
Java is openjdk 11 IIRC and I'll check lein ASAP

**Comment by faxm0dem** [comment]
I had never updated my ancient lein script since upgrading from strech to buster.
Never mind me and sorry for the noise!
